services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  back-end:
    build:
      context: ./back-end
    ports:
      - "${API_PORT}:3001"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy

  front-end:
    build:
      context: ./front-end-nextjs
    ports:
      - "${PORT}:3000"
    volumes:
      - ./front-end-nextjs:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:${API_PORT}
    depends_on:
      - back-end

volumes:
  mysql_data:
  mysql_config: