version: '3.3'
services:
  back-end:
    build:
      context: ./back-end
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./back-end:/app
    env_file:
      - ./.env
    depends_on:
      - db
  front-end:
    build:
      context: ./front-end
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./front-end:/app
    env_file:
      - ./.env
    depends_on:
      - back-end
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql_data:
  mysql_config: